<table class="table">
  <?php if ($this->offer->getSalestype() == 'buy') : ?>
    <tr>
      <td class="width-25"><?= __('Sales price', 'casawp') ?></td>
      <td class="width-75">
        <?= $this->offer->renderPrice() ?>
      </td>
    </tr>
  <?php endif; ?>
  <?php if ($this->offer->getSalestype() == 'rent') : ?>
    <?php if ($this->offer->getFieldValue('grossPrice', false)): ?>
       <tr>
          <td class="width-25"><?= __('Gross price','casawp') ?></td>
          <td class="width-75">
            <?= $this->offer->renderPrice('gross'); ?>
          </td>
        </tr>
    <?php endif ?>
    <?php if ($this->offer->getFieldValue('netPrice', false)): ?>
       <tr>
          <td class="width-25"><?= __('Net price','casawp') ?></td>
          <td class="width-75">
            <?= $this->offer->renderPrice('net'); ?>
          </td>
        </tr>
    <?php endif ?>

    <!-- Mietkaution ? (untested)  -->
    <?php /*
    $deposit = $this->offer->getNumval('rental_deposit');
    if ($deposit) : ?>
      <tr>
         <td class="width-25"><?= __('Rental deposit','casawp') ?></td>
         <td class="width-75">
           <?= $deposit; ?>
         </td>
       </tr>
    <?php endif; */ ?>

  <?php endif; ?>

  <?php global $casawp; ?>
  <?php foreach ($this->offer->getExtraCosts() as $cost): ?>
    <tr>
      <td class="width-25">Nebenkosten:</td>
      <td class="width-75"><?= $casawp->renderPrice($cost['price'], $cost['currency'], $cost['propertysegment'], $cost['timesegment']); ?></td>
    </tr>
    <?php break; ?>
  <?php endforeach ?>
  <tr>
    <td class="width-25"><?= __('Available from:','casawp') ?></td>
    <td class="width-75">
      <?= $this->offer->renderAvailabilityDate() ?>
    </td>
  </tr>
</table>
