<!-- 
    $this->images
    $this->offer
-->


<div class="casawp-slider-currentimage" id="slider">
  <div class="row-fluid">
    <div class="span12" id="carousel-bounding-box">
      <div id="casawpCarousel" class="carousel slide">
        <div class="carousel-inner">
        <?php
          $i = 0;
          foreach ($this->images as $i => $image) :
            $i++;
        ?>
            <div class="<?= $i == 1 ? 'active' : ''; ?> item" data-slide-number=" <?= $i-1; ?>">
              <?php $thumbimgL = wp_get_attachment_image( $image->ID, 'full', true ); ?>
              <?php $img_url = wp_get_attachment_image_src( $image->ID, 'full' ); ?>
              <a href="<?= $img_url[0] ?>" class="property-image-gallery" rel="casawp-single-gallery"><?= $thumbimgL; ?></a>
              <div id="carousel-text" class="carousel-caption" >
              <?php if ($image->post_excerpt) : ?>
                <p><?= $image->post_excerpt ?></p>
              <?php endif; ?>
              </div>
            </div>
          <?php endforeach ?>
          
        </div>
        <a class="casawp-carousel-left" href="#casawpCarousel" data-slide="prev"><i>‹</i></a>
        <a class="casawp-carousel-right" href="#casawpCarousel" data-slide="next"><i>›</i></a>

      </div>
    </div>
  </div>
</div>
