
<?php // show title only when at least one share option is active ?>
<?php if (get_option( 'casasync_share_facebook', false )) : ?>
<h3><i class="fa fa-share-square"></i> <?= __('Share', 'casawp') ?></h3>
<?php endif; ?>

<?php if (get_option( 'casasync_share_facebook', false )) : ?>
	<div class="fb-like" data-send="true" data-layout="button_count" data-href="http://<?=$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'] ?>" data-width="200" data-show-faces="true"></div><br>
<?php endif; ?>