<?php if ($this->offer->getFieldValue('address_streetaddress') && $this->offer->getFieldValue('property_geo_latitude')) : ?>
	<!--
		Font Awesome is in following flavours available
		Free Solid
		Free Regular
		Pro light
		Pro Solid
	-->
	<h1>Map Distance POC</h1>
	<div class="casadistance"
		id="casadistance"
		data-lat = "47.639730"
		data-lng = "8.939080"
		data-zoom="10"
		data-marker-size="60px"
		data-marker-icon="faMapMarkerAlt"
		data-marker-color="#A58962"
		data-marker-title="some title"
		data-marker-poi-size="20px"
		data-marker-poi-color="#A58962"
		data-marker-poi-active-color="#d63a7a"
		data-marker-poi-text-color="#ffffff"
		data-locale="de"
		data-template-listitem-content='
            <span class="fa-layers fa-fw" style="">
                <i class="far fa-circle"></i>
                <span class="fa-layers-text" data-fa-transform="shrink-5" style="">{{number}}</span>
            </span>
            <h4 class="casadistance__listitem__title">{{title}}<span class="casadistance__listitem__subtitle">{{subtitle}}</span></h4>
        '
        data-template-distance-result-item='
            <div>{{{icon}}} {{distance}} {{duration}}</div>
        '		
        data-template-distance-result-item-close-btn-content='X'
        data-distance-timetable-title='Fahrplan'
        data-template-distance-timetable-item='
        	<li class="casadistance__timetable__listitem">
        		<div class="casadistance__timetable__listitem__departure">{{departure}}</div>
        		<div class="casadistance__timetable__listitem__name">{{name}}</div>
        		<div class="casadistance__timetable__listitem__to">{{to}}</div>
        	</li>
        		
        '
		data-styles='[
			{
			"elementType": "geometry",
			"stylers": [
			  {
			    "color": "#f5f5f5"
			  }
			]
			},
			{
			"elementType": "labels.icon",
			"stylers": [
			  {
			    "visibility": "off"
			  }
			]
			},
			{
			"elementType": "labels.text.fill",
			"stylers": [
			  {
			    "color": "#616161"
			  }
			]
			},
			{
			"elementType": "labels.text.stroke",
			"stylers": [
			  {
			    "color": "#f5f5f5"
			  }
			]
			},
			{
			"featureType": "administrative.land_parcel",
			"elementType": "labels.text.fill",
			"stylers": [
			  {
			    "color": "#bdbdbd"
			  }
			]
			},
			{
			"featureType": "poi",
			"elementType": "geometry",
			"stylers": [
			  {
			    "color": "#eeeeee"
			  }
			]
			},
			{
			"featureType": "poi",
			"elementType": "labels.text.fill",
			"stylers": [
			  {
			    "color": "#757575"
			  }
			]
			},
			{
			"featureType": "poi.park",
			"elementType": "geometry",
			"stylers": [
			  {
			    "color": "#e5e5e5"
			  }
			]
			},
			{
			"featureType": "poi.park",
			"elementType": "labels.text.fill",
			"stylers": [
			  {
			    "color": "#9e9e9e"
			  }
			]
			},
			{
			"featureType": "road",
			"elementType": "geometry",
			"stylers": [
			  {
			    "color": "#ffffff"
			  }
			]
			},
			{
			"featureType": "road.arterial",
			"elementType": "labels.text.fill",
			"stylers": [
			  {
			    "color": "#757575"
			  }
			]
			},
			{
			"featureType": "road.highway",
			"elementType": "geometry",
			"stylers": [
			  {
			    "color": "#dadada"
			  }
			]
			},
			{
			"featureType": "road.highway",
			"elementType": "labels.text.fill",
			"stylers": [
			  {
			    "color": "#616161"
			  }
			]
			},
			{
			"featureType": "road.local",
			"elementType": "labels.text.fill",
			"stylers": [
			  {
			    "color": "#9e9e9e"
			  }
			]
			},
			{
			"featureType": "transit.line",
			"elementType": "geometry",
			"stylers": [
			  {
			    "color": "#e5e5e5"
			  }
			]
			},
			{
			"featureType": "transit.station",
			"elementType": "geometry",
			"stylers": [
			  {
			    "color": "#eeeeee"
			  }
			]
			},
			{
			"featureType": "water",
			"elementType": "geometry",
			"stylers": [
			  {
			    "color": "#c9c9c9"
			  }
			]
			},
			{
			"featureType": "water",
			"elementType": "labels.text.fill",
			"stylers": [
			  {
			    "color": "#9e9e9e"
			  }
			]
			}
		]'
	>
		<div id="casadistancePointOfInterest" class="casadistance__menu">
			<ul class="casadistance__menu__list">
				<!-- <li><input type="button" id="kindergarten" value="Kindergarten" /></li> -->
				<li class="casadistance__menu__item"><button class="casadistance__menu__button" id="casadistanceShowSchools">Schule</button></li>
				<li class="casadistance__menu__item"><button class="casadistance__menu__button" id="casadistanceShowPublicTransports">ÖV</button></li>
				<li class="casadistance__menu__item"><button class="casadistance__menu__button" id="casadistanceShowAirports">Flughafen</button></li>
				<li class="casadistance__menu__item"><button class="casadistance__menu__button" id="casadistanceShowShopping">Einkaufen</button></li>
			</ul>
		</div>

		<div id="casadistanceMap" class="casadistance__map"></div>
		<div class="casadistance__result">
			<div class="casadistance__result__list" id="casadistanceResultList"></div>
			<div class="casadistance__result__content" style="width: 50%; float: left;" id="casadistanceContent"></div>
		</div>
	</div>
<?php endif; ?>