<?php if ($sent): ?>
	<p class="alert alert-success">Danke Ihre Nachricht wurde versendet.</p>
<?php else: ?>

	<?php $renderobject = ($this->offer ? $this->offer : $this->casawp); ?>

	<?php if ($offer || $project): ?>
			<?php $form->setAttribute('action', get_permalink(($offer ? $offer->post : $project->post))); ?>
	<?php endif; ?>


	<?= $this->form()->openTag($form->setAttribute('class', 'casawp-contactform-form')); ?>
	<?= $this->formElement($form->get('form_id')) ?>
	<?php wp_nonce_field( 'send-inquiry' ); ?>
	<input id="theApsoluteRealEmailField" type="text" name="email" value="" placeholder="NlChT8 AuSf$lLeN">

	<div class="casawp-gender-radios">
		<?= $renderobject->renderContactFormElement($form->get('gender'), $form) ?>
	</div>
	<div class="casawp-row">
		<div class="col-md-5 casawp-input-left">
			<?= $renderobject->renderContactFormElement($form->get('firstname'), $form) ?>
		</div>
		<div class="col-md-7 casawp-input-right">
			<?= $renderobject->renderContactFormElement($form->get('lastname'), $form) ?>
		</div>
	</div>
	<?= $renderobject->renderContactFormElement($form->get('street'), $form) ?>
	<div class="casawp-row">
		<div class="col-md-5 casawp-input-left">
			<?= $renderobject->renderContactFormElement($form->get('postal_code'), $form) ?>
		</div>
		<div class="col-md-7 casawp-input-right">
			<?= $renderobject->renderContactFormElement($form->get('locality'), $form) ?>
		</div>
	</div>
	<?= $renderobject->renderContactFormElement($form->get('country'), $form) ?>
	<?= $renderobject->renderContactFormElement($form->get('phone'), $form) ?>
	<?= $renderobject->renderContactFormElement($form->get('emailreal'), $form) ?>
	<?= $renderobject->renderContactFormElement($form->get('message'), $form) ?>

	<?php if (get_option('casawp_recaptcha') && get_option('casawp_recaptcha_secret') && !get_option('casawp_recaptcha_v3')): ?>
		<div class="g-recaptcha" data-sitekey="<?php echo get_option('casawp_recaptcha') ?>"></div>
		<div id="recaptchaerror" <?php echo (!$invalidCaptcha ? 'style="display: none;"' : '') ?> class="alert alert-danger" role="alert">
			<?php echo __('Invalid reCAPTCHA response!', 'casawp') ?>
		</div>
		<div id="casawpRecaptcha"></div>
		<script>
			window.captchaKey = '<?php echo escapeJavaScriptText(get_option('casawp_recaptcha')); ?>';
		</script>
		<script>
			var onloadCallback = function() {
				grecaptcha.render('casawpRecaptcha', {
				'sitekey' : window.captchaKey
				});
			};
		</script>
		<script src="https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit"
			async defer>
		</script>
	<?php elseif(get_option('casawp_recaptcha') && get_option('casawp_recaptcha_secret') && get_option('casawp_recaptcha_v3')): ?>
		<div class="g-recaptcha-v3" data-sitekey="<?php echo get_option('casawp_recaptcha') ?>"></div>
		<script src="https://www.google.com/recaptcha/api.js?render=<?php echo get_option('casawp_recaptcha') ?>"></script>
		<input type="hidden" id="gRecaptchaResponse" name="g-recaptcha-response">
		<script>
			window.captchaKey = '<?php echo $form->escapeJavaScriptText(get_option('casawp_recaptcha')); ?>';
		</script>
		<script>

			var form = document.getElementById("casawpPropertyContactForm");

			form.addEventListener('submit', event => {
				event.preventDefault()
				validate(form)
			});

			function validate(form) {
				getRecaptchaToken(form)
			}

			function getRecaptchaToken(form) {
				grecaptcha.ready(function() {
					grecaptcha.execute(window.captchaKey, {action: 'casawpPropertyContactForm'}).then(function(token) {
						gRecaptchaResponse.value = token //set the value of the hidden field
						form.submit() //submit the form
					});
				});
			}
			
		</script>

	<?php endif; ?>

	<div class="row">
	    <div class="col-md-7 casawp-input-left">
	        <p class="casawp-form-control-static casawp-text-muted casawp-small"><?= __("Please fill out all the fields.", "casawp") ?></p>
	    </div>
	    <div class="col-md-5 casawp-input-right">
	        <input type="submit" class="casawp-contactform-send" value="<?= __("Send", "casawp") ?>">
	    </div>
	    <div class="clearBoth"></div>
	</div>

	<?php 
	/*echo '<pre>';
		print_r($form->getMessages());
	echo '</pre>';*/
	 ?>

	<?= $this->form()->closeTag(); ?>

<?php endif ?>
