<?php
	$required = false;
	if ($form) {
		$required = $form->getInputFilter()->get($element->getName())->isRequired();
	}
?>

<div class="form-group <?php if($required) echo "is-required" ?> <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
	<label for="contactForm<?php echo $element->getName() ?>" class="control-label"><?php echo $element->getLabel() ?></label>
	<?php echo $this->formElement($element
		->setAttribute('class', 'form-control casawp-form-control ' . ($this->formElementErrors($element) ? "is-invalid" : ""))
		->setAttribute("id", "contactForm" . $element->getName())
	); ?>
	<?php if ($this->formElementErrors($element)): ?>
		<div class="invalid-feedback"><?php echo $this->formElementErrors($element) ?></div>
	<?php endif ?>
</div>