<?php if ($sent): ?>
	<p class="alert alert-success">Danke Ihre Nachricht wurde versendet.</p>
<?php else: ?>

	<?php $renderobject = ($this->offer ? $this->offer : $this->casawp); ?>

	<?php if ($offer || $project): ?>
			<?php $form->setAttribute('action', get_permalink(($offer ? $offer->post : $project->post))); ?>
	<?php endif; ?>


	<?= $this->form()->openTag($form->setAttribute('class', 'casawp-contactform-form')); ?>
	<?= $this->formElement($form->get('form_id')) ?>
	<?php wp_nonce_field( 'send-inquiry' ); ?>
	<input id="theApsoluteRealEmailField" type="text" name="email" value="" placeholder="NlChT8 AuSf$lLeN">

	<div class="casawp-gender-radios">
		<?= $renderobject->renderContactFormElement($form->get('gender'), $form) ?>
	</div>
	<div class="casawp-row">
		<div class="col-md-5 casawp-input-left">
			<?= $renderobject->renderContactFormElement($form->get('firstname'), $form) ?>
		</div>
		<div class="col-md-7 casawp-input-right">
			<?= $renderobject->renderContactFormElement($form->get('lastname'), $form) ?>
		</div>
	</div>
	<?= $renderobject->renderContactFormElement($form->get('street'), $form) ?>
	<div class="casawp-row">
		<div class="col-md-5 casawp-input-left">
			<?= $renderobject->renderContactFormElement($form->get('postal_code'), $form) ?>
		</div>
		<div class="col-md-7 casawp-input-right">
			<?= $renderobject->renderContactFormElement($form->get('locality'), $form) ?>
		</div>
	</div>
	<?= $renderobject->renderContactFormElement($form->get('country'), $form) ?>
	<?= $renderobject->renderContactFormElement($form->get('phone'), $form) ?>
	<?= $renderobject->renderContactFormElement($form->get('emailreal'), $form) ?>
	<?= $renderobject->renderContactFormElement($form->get('message'), $form) ?>

	<div class="row">
    <div class="col-md-7 casawp-input-left">
        <p class="casawp-form-control-static casawp-text-muted casawp-small"><?= __("Please fill out all the fields.", "casawp") ?></p>
    </div>
    <div class="col-md-5 casawp-input-right">
        <input type="submit" class="casawp-contactform-send" value="<?= __("Send", "casawp") ?>">
    </div>
    <div class="clearBoth"></div>
	</div>

	<?= $this->form()->closeTag(); ?>

<?php endif ?>
