<div class="form-group <?php if($this->formElementErrors($element)) echo "has-warning" ?>">
	<label class="control-label"><?php echo $element->getLabel() ?></label>
	<?php 
		$classes[] = 'form-control'; 
		if ($this->formElementErrors($element)) {
			$classes[] = 'form-control-warning';
		}
		$ex_classes = explode(' ', $element->getAttribute('class')); 
		if ($ex_classes) {
			$classes = array_merge($classes, $ex_classes);
		}
		$class_str = implode(' ', $classes);
	?>
	<?php echo $this->formElement($element->setAttribute('class', $class_str)); ?>
	<?php if ($this->formElementErrors($element)): ?>
		<span class="help-block"><?php echo $this->formElementErrors($element) ?></span>
	<?php endif ?>
</div>