<?php
	$required = false;
	if ($form) {
		$required = $form->getInputFilter()->get($element->getName())->isRequired();
	}
?>

<div class="form-group <?php if($required) echo "is-required" ?> <?php if($this->formElementErrors($element)) echo "has-error has-feedback" ?>">
	<label for="contactForm<?php echo $element->getName() ?>" class="control-label"><?php echo $element->getLabel() ?></label>
	<?php echo $this->formElement($element
		->setAttribute('class', 'form-control casawp-form-control')
		->setAttribute("id", "contactForm" . $element->getName())
	); ?>
	<?php if ($this->formElementErrors($element)): ?>
		<span class="help-block"><?php echo $this->formElementErrors($element) ?></span>
	<?php endif ?>
</div>