<?php if ($this->offer->getFieldValue('address_streetaddress') && $this->offer->getFieldValue('property_geo_latitude')) : ?>
	<?php if(get_option('casawp_single_use_zoomlevel') != '0') : ?>
		<?php if (get_option('casawp_load_maps_on_click', false)): ?>
			<div class="casawp-map__placeholder" id="casawp-mapPlaceholder">
				<button class="casawp-map__placeholder__show-btn" id="casawp-mapShowBtn">Click me to load</button>
			</div>
		<?php endif ?>
		<?php $map_url = "https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=" . substr(get_locale(), 0, 2)  . "&amp;geocode=&amp;q=" . $this->offer->getFieldValue('property_geo_latitude') .','.$this->offer->getFieldValue('property_geo_longitude') . "&amp;aq=&amp;ie=UTF8&amp;hq=&amp;hnear=" . $this->offer->getFieldValue('property_geo_latitude') .',' . $this->offer->getFieldValue('property_geo_longitude') . "&amp;t=m&amp;z=12"; ?>
		<div class="casawp-map" style="display:none" <?php if (get_option('casawp_load_maps_on_click', false)): ?>
			data-load-map-on-click="true"
		<?php else: ?>
			data-load-map-on-click="false"
		<?php endif ?> data-lat="<?= $this->offer->getFieldValue('property_geo_latitude') ?>" data-lng="<?= $this->offer->getFieldValue('property_geo_longitude') ?>"><div id="map-canvas" style="width:100%; height:400px;" ></div></div>
	<?php endif; ?>
<?php endif; ?>

