<div class="row">
	<nav class="casawp-single-pagination-top">
		<?php echo $offer->renderPagination(); ?>
	</nav>
</div>
<div class="row">
	<div class="casawp-single-content">
		<header class="casawp-single-header">
			<h1 class="casawp-single-title"><?php echo $offer->getTitle() ?></h1>
		</header>
		<div class="casawp-single-contentarea">
			<?php echo $offer->renderGallery(); ?>
			<br>
			<?php echo $offer->renderTabable(); ?>
			<?php //echo $offer->contactSellerByMailBox(); ?>
		</div>
	</div>
	<aside class="casawp-single-aside">
		<div class="casawp-single-aside-container">
			<?php echo $offer->renderPagination(); ?>
		</div>
		<div class="casawp-single-aside-container casawp-virtual-tour-btn">
			<?php 
				$urls = $offer->renderUrls();
				if ($urls && array_key_exists('virtual-tour', $urls)) {
					foreach ($urls['virtual-tour'] as $key => $url) {
						echo '<a class="btn btn-default btn-block" href="'.$url['href'].'" tarrender="_blank" title="'.$url['title'].'">'. ($url['label'] ? $url['label'] : __('Virtual Tour', 'casawp')) .'</a>';
					}
				}
			?>
		</div>
		<div class="casawp-single-aside-container">
			<?php if ($offer->getAvailability() !== 'reference'): ?>
				<?php echo $offer->renderContactform(); ?>
			<?php endif; ?>
		</div>
		<div class="casawp-single-aside-container">
			<?php echo $offer->renderSeller(); ?>
		</div>
		<div class="casawp-single-aside-container">
			<?php echo $offer->renderSalesPerson(); ?>
		</div>
		<div class="casawp-single-aside-container">
			<?php echo $offer->renderVisitPerson(); ?>
		</div>
		<div class="casawp-single-aside-container">
			<?php echo $offer->renderAllShareWidgets(); ?>
		</div>
	</aside>
</div>