<div class="casasync-basic-box">
  <div>
    <h4><?= $offer->renderCategoryLabels() ?></h4>
    <?= $offer->renderDatapoints('single') ?>
  </div>
</div>
<div class="casasync-basic-box">
  <div>
    <h4><?= __("Address", 'casasync') ?></h4>
    <?= $offer->renderAddress() ?>
  </div>
</div>
<div class="casasync-basic-box">
  <div>
      <?= $price_title = ($offer->type == 'rent') ? (__('rent', 'casasync')) : (__('Price', 'casasync')); ?>
      <h4><?= $price_title ?></h4>  
  </div>
</div>