<table class="table">
  <?php if ($this->main_basis == 'buy') : ?>
    <tr>
      <td class="width-25"><?= __('Sales price', 'casasync') ?></td>
      <td class="width-75">
        <?php $this->getPrice('sales') ? $this->getPrice('sales', 'full') : __('On Request', 'casasync'); ?>
      </td>
    </tr>
  <?php endif; ?>
  <?php if ($this->main_basis == 'rent') : ?>
    <?php if ( $this->getPrice('gross') || $this->getPrice('net')  ) : ?>
      <?php if ($this->getPrice('gross')) : ?>
        <tr>
          <td class="width-25"><?= __('Gross price','casasync') ?></td>
          <td class="width-75">
            <?= $this->getPrice('gross', 'full'); ?>
          </td>
        </tr>
      <?php endif; ?>
      <?php if ($this->getPrice('net')) : ?>
        <tr>
          <td class="width-25"><?= __('Net price','casasync') ?></td>
          <td class="width-75">
            <?= $this->getPrice('net', 'full') ?>
          </td>
        </tr>
      <?php else : ?>
        <tr>
          <td class="width-25"><?= __('Rent price','casasync') ?></td>
          <td class="width-75">
            <?= __('On Request', 'casasync') ?>
          </td>
        </tr>
      <?php endif; ?>
    <?php endif; ?>
  <?php endif; ?>
  <?php if ($this->getExtraCosts('Nebenkosten')) : ?>
    <tr>
      <td class="width-25"><?= __('Additional costs', 'casasync') ?></td>
      <td class="width-75"><?= $this->getExtraCosts('Nebenkosten') ?></td>
    </tr>
  <?php endif; ?>
  <?php if ($this->the_availability) : ?>
    <tr>
      <td class="width-25"><?= __('Available from:','casasync') ?></td>
      <td class="width-75">
        <?= $this->formatStartdate($this->start); ?>
      </td>
    </tr>
  <?php endif; ?>
</table>