<!-- $urls = $this->getUrls(); -->
<?php $urls = false ?>

<ul class="casasync-tabable-nav">
  <li class="active"><a data-toggle="tab" href="#text_basics"><small><?= __("Base data", 'casasync') ?></small></a></li>
  <li><a data-toggle="tab" href="#text_description"><small><?= __('Description', 'casasync') ?></small></a></li>
  <?php if ($urls && array_key_exists('youtube', $urls)) : ?>
    <li><a data-toggle="tab" href="#tab_videos"><small><?= __('Videos', 'casasync') ?></small></a></li>
  <?php endif; ?>
  <li><a data-toggle="tab" href="#text_numbers"><small><?= __("Specifications", 'casasync') ?></small></a></li>
</ul>

<div class="casasync-tabable-content">

  <div class="casasync-tabable-pane active in" id="text_basics">
    <div class="casasync-basic-boxes">
        <?= $this->offer->renderBasicBoxes(); ?>
    </div>
    {{Map}}
    <!-- $content .= $this->getMap(); -->
  </div>


  <div class="casasync-tabable-pane" id="text_description">
    <?= $this->offer->content ?>
    {{description}}
  </div>


  <!-- if ($urls && array_key_exists('youtube', $urls)) {
    <div class="casasync-tabable-pane" id="tab_videos">
    global $wp_embed;
    foreach ($urls['youtube'] as $key => $url) {
      <div class="casasync-youtube-video-wrapper embed-responsive embed-responsive-16by9">
      $content .= $wp_embed->run_shortcode('[embed]'.$url['href'].'[/embed]'); 
      </div>
    }
    </div>
  } -->

  <div class="casasync-tabable-pane" id="text_numbers">
    {{details}}
    <!-- $content .= $this->getSpecificationsTable(); -->
  </div>

</div>




