<div class="casawp-filterform-wrap large">
	<h3><?= __('Advanced Search', 'casawp') ?></h3>
	<?= $this->form()->openTag($form->setAttribute('class', 'casawp-filterform')); ?>
		
	<?php if ($form->getAvailabilityOptions()): ?>
		    <?php echo $this->formElement($form->get('availabilities')->setAttribute('style', 'display:none')); ?>
	<?php endif ?>	

	<?php if ($form->getSalestypeOptions()): ?>
		<?php echo $this->formElement($form->get('salestypes')->setAttribute('class', 'form-control chosen-select')->setAttribute('data-placeholder', 'Vermarktungsart wählen')); ?>
	<?php endif ?>
	
	<?php if ($form->getCategoryOptions()): ?>
		<?php echo $this->formElement($form->get('categories')->setAttribute('class', 'form-control chosen-select')->setAttribute('data-placeholder', 'Kategorie wählen')); ?>
	<?php endif ?>

	<?php if ($form->getLocationOptions()): ?>
		<?php echo $this->formElement($form->get('locations')->setAttribute('class', 'form-control chosen-select')->setAttribute('data-placeholder', 'Ortschaft wählen')); ?>
	<?php endif ?>

	
	
	<input type="submit" class="casawp-filterform-button" value="<?= __('Search') ?>">

	<?= $this->form()->closeTag(); ?>
	<div class="clearfix"></div>
</div>