<?php if ($sent): ?>
	<p class="alert alert-success">Danke Ihre Nachricht wurde versendet.</p>	
<?php else: ?>
	
	<?php $renderobject = ($this->offer ? $this->offer : $this->casawp); ?>

	<?php $form->setAttribute('action', get_permalink(($offer ? $offer->post : $project->post))); ?>

	<?= $this->form()->openTag($form->setAttribute('class', 'casawp-contactform-form')); ?>
	<?php wp_nonce_field( 'send-inquiry' ); ?>
	<input id="theApsoluteRealEmailField" type="text" name="email" value="" placeholder="NlChT8 AuSf$lLeN">
	<div class="casawp-row">
		<div class="casawp-col-md-5 casawp-input-left">
			<?= $renderobject->renderContactFormElement($form->get('firstname')) ?>
		</div>
		<div class="casawp-col-md-7 casawp-input-right">
			<?= $renderobject->renderContactFormElement($form->get('lastname')) ?>
		</div>
	</div>
	<?= $renderobject->renderContactFormElement($form->get('street')) ?>
	<div class="casawp-row">
		<div class="casawp-col-md-5 casawp-input-left">
			<?= $renderobject->renderContactFormElement($form->get('postal_code')) ?>
		</div>
		<div class="casawp-col-md-7 casawp-input-right">
			<?= $renderobject->renderContactFormElement($form->get('locality')) ?>
		</div>
	</div>
	<?= $renderobject->renderContactFormElement($form->get('country')) ?>
	<?= $renderobject->renderContactFormElement($form->get('phone')) ?>
	<?= $renderobject->renderContactFormElement($form->get('emailreal')) ?>
	<?= $renderobject->renderContactFormElement($form->get('message')) ?>

	<div class="casawp-row">
        <div class="casawp-col-md-7 casawp-input-left">
            <p class="casawp-form-control-static casawp-text-muted casawp-small"><?= __("Please fill out all the fields.", "casawp") ?></p>
        </div>
        <div class="casawp-col-md-5 casawp-input-right">
            <input type="submit" class="casawp-contactform-send" value="<?= __("Send", "casawp") ?>">
        </div>
        <div class="clearBoth"></div>
	</div>

	<?= $this->form()->closeTag(); ?>

<?php endif ?>