<table class="table">
  <?php if ($this->offer->getSalestype() == 'buy') : ?>
    <tr>
      <td class="width-25"><?= __('Sales price', 'casawp') ?></td>
      <td class="width-75">
        <?php
          if ($this->offer->getFieldValue('price', false)) {
            echo $this->offer->renderPrice();
          } else {
            echo __('On Request', 'casawp');
          }
        ?>
      </td>
    </tr>
  <?php endif; ?>
  <?php if ($this->offer->getSalestype() == 'rent') : ?>
    <?php if ($this->offer->getFieldValue('grossPrice', false)): ?>
        <tr>
          <td class="width-25"><?= __('Gross price','casawp') ?></td>
          <td class="width-75">
            <?= $this->offer->renderPrice('gross'); ?>
          </td>
        </tr>
    <?php elseif ($this->offer->getFieldValue('netPrice', false)): ?>
        <tr>
          <td class="width-25"><?= __('Net price','casawp') ?></td>
          <td class="width-75">
            <?= $this->offer->renderPrice('net'); ?>
          </td>
        </tr>
    <?php else: ?>
        <tr>
          <td class="width-25"><?= __('Rent price','casawp') ?></td>
          <td class="width-75">
            <?= __('On Request', 'casawp'); ?>
          </td>
        </tr>
    <?php endif ?>

    <?php
    $deposit = $this->offer->getNumval('rental_deposit');
    if ($deposit) : ?>
      <tr>
         <td class="width-25"><?= $deposit->getLabel() ?></td>
         <td class="width-75">
           <?= $casawp->renderPrice($deposit->getValue(), 'CHF', 'all', 'infinite'); ?>
         </td>
       </tr>
    <?php endif;  ?>

  <?php endif; ?>

  <?php global $casawp; ?>
  <?php foreach ($this->offer->getExtraCosts() as $cost): ?>
    <tr>
      <td class="width-25"><?= __('Extra Costs:', 'casawp') ?></td>
      <td class="width-75"><?= $casawp->renderPrice($cost['price'], $cost['currency'], $cost['propertysegment'], $cost['timesegment']); ?></td>
    </tr>
    <?php break; ?>
  <?php endforeach ?>
  <tr>
    <td class="width-25"><?= __('Available from:','casawp') ?></td>
    <td class="width-75">
      <?= $this->offer->renderAvailabilityDate() ?>
    </td>
  </tr>
</table>
