<table class="table">
  <?php if ($this->offer->getSalestype() == 'buy') : ?>
    <tr>
      <td class="width-25"><?= __('Sales price', 'casawp') ?></td>
      <td class="width-75">
        <?= $this->offer->renderPrice() ?>
      </td>
    </tr>
  <?php endif; ?>
  <?php if ($this->main_basis == 'rent') : ?>
    <?php if ($this->offer->renderPrice('gross')): ?>
       <tr>
          <td class="width-25"><?= __('Gross price','casawp') ?></td>
          <td class="width-75">
            <?= $this->offer->renderPrice('gross'); ?>
          </td>
        </tr>
    <?php endif ?>
    <?php if ($this->offer->renderPrice('net')): ?>
       <tr>
          <td class="width-25"><?= __('Net price','casawp') ?></td>
          <td class="width-75">
            <?= $this->offer->renderPrice('net'); ?>
          </td>
        </tr>
    <?php endif ?>
  <?php endif; ?>

  <?php //todo ?>
  <?php if (0==1&&$this->getExtraCosts('Nebenkosten')) : ?>
    <tr>
      <td class="width-25"><?= __('Additional costs', 'casawp') ?></td>
      <td class="width-75"><?= $this->getExtraCosts('Nebenkosten') ?></td>
    </tr>
  <?php endif; ?>

  <tr>
    <td class="width-25"><?= __('Available from:','casawp') ?></td>
    <td class="width-75">
      <?= $this->offer->renderAvailabilityDate() ?>
    </td>
  </tr>
</table>