<?php global $casawp; ?>
<?php if ($this->integratedOffers): ?>
  <section class="casawp-integrated-offers">
    <h2>Zusatz Angebote</h2>
    <?php foreach ($this->integratedOffers as $offer): ?>
      <article class="casawp-integrated-offer">
        <h3><?= $offer['type'] ?> <?= ($offer['count'] > 1 ? 'x'.$offer['count']: '') ?></h3>
        <strong><?= $casawp->renderPrice($offer['price'], $offer['currency'], $offer['propertysegment'], $offer['timesegment']) ?></strong>
        <?php if ($offer['inclusive']): ?>
          Im Hauptangebot integriert
        <?php endif ?>
      </article>
    <?php endforeach ?>
  </section>
  <br>
  <br>
  <br>
<?php endif ?>