<div class="casawp-project">
	<section class="section text-image-section light">
		<div class="container">
			<div class="row">
				<div class="hidden-md hidden-lg col-sm-24 reveal animated fadeIn" style="">
					<div>
						<img src="http://dev.stalderstalder.ch/wp-content/uploads/2016/02/bannaebnisued_EgEUmWa.jpg.1000x999_q85.jpg" alt="" class="img-responsive">
					</div>
				</div>
				<div class="col-lg-8 col-md-10 col-sm-20 spacing-sm spacing-xs-small reveal animated fadeIn" data-delay="800">
					
					<h2 class="section-title limited" style="border-color: #fcc41e;">
						<a href="<?= get_permalink($project->post) ?>"><?= $project->getTitle(); ?></a>
					</h2>
					<p>Projektenwicklung und Vermarktung.</p>
					<h4>Ausgangslage:</h4>
					<p>75 000 m2&nbsp;Landwirtschaftsland mit Siedlungspotenzial sollen auf Wunsch der Eigentümerschaften eingezont und einer baulichen Nutzung zugeführt werden.</p>
					<h4>Unsere Dienstleistungen:</h4>
					<p>Erste&nbsp;Studien und Einbezug der Behörden,&nbsp;Quartiergestaltungsplan, Einzonung der ersten Etappe (Bannäbni Süd, ca. 35 000 m2), Bebauungsplan über diese erste Etappe, Haupt- und Detailerschliessung, Erreichen der Baureife und Marktreife.</p>
					<h4>Stand heute:</h4>
					<p>Vermarktung&nbsp;von 16 Baulandparzellen und 18 freistehenden Einfamilienhäusern.</p>
					<div class="arrow-link-wrapper">
						<em><a class="arrow-link-right" title="www.bannaebnisued.ch" href="http://bannaebnisued.ch/" target="_blank">www.bannaebnisued.ch</a></em>
					</div>
				</div>
				<div class="hidden-xs hidden-sm col-lg-16 col-md-14">
					<div class="reveal animated fadeIn">
						<img src="http://dev.stalderstalder.ch/wp-content/uploads/2016/02/bannaebnisued_EgEUmWa.jpg.1000x999_q85.jpg" alt="" class="img-responsive">
					</div>
				</div>
			</div>
		</div>
	</section>
</div>
<hr class="soften">

<?php 
	/*
		<div class="casawp-thumbnail-wrapper">
			<?php echo (has_post_thumbnail( $project->post->ID ) ? $project->renderFeaturedImage() : '<div class="casawp-missing-gallery">' . __('No image', 'casawp') . '</div>'); ?>
		</div>
		<div class="casawp-text">
			<h3><a href="<?= get_permalink($project->post) ?>"><?php echo $project->getTitle(); ?></a></h3>
		</div>
	*/
?>