<?php $pattern = '<tr><th>{{label}}</th><td>{{value}}</td></tr>' ?>
<?php $pattern_2 = '<tr><td colspan="2">{{value}}</td></tr>' ?>

<table class="table">
  <tbody>
    <?php 
      foreach ($datapoints as $datapoint){
        $field = substr($datapoint, strlen('casawp_archive_show_'));
        switch ($field) {
          case 'street_and_number':
            $point = str_replace('{{label}}', __('Street', 'casawp'), $pattern);
            echo str_replace('{{value}}', trim($this->offer->getFieldValue('property_address_streetaddress') . ' ' . $this->offer->getFieldValue('property_address_streetnumber')), $point);
            break;
          case 'location':
            $point = str_replace('{{label}}', __('Locality', 'casawp'), $pattern);
            echo str_replace('{{value}}', trim($this->offer->getFieldValue('address_postalcode') . ' ' . $this->offer->getFieldValue('address_locality')), $point);
            break;
          case 'surface_property':
            $numval = $this->offer->getNumval('area_sia_gsf');
            if ($numval) {
              $point = str_replace('{{label}}', $numval->getLabel(), $pattern);
              echo str_replace('{{value}}', $this->offer->renderNumvalValue($numval), $point);
            }
            break;
          case 'price':
            if ($this->offer->getAvailablility() != 'reference') {
              if ($this->offer->getSalestype() == 'buy') {
                $point = str_replace('{{label}}', __('Sales price', 'casawp'), $pattern);
                echo str_replace('{{value}}', $this->offer->renderPrice(), $point);
              }
              if ($this->offer->getSalestype() == 'rent') {
                if ($this->offer->getFieldValue('grossPrice', false)) {
                  $point = str_replace('{{label}}', __('Gross price', 'casawp'), $pattern);
                  echo str_replace('{{value}}', $this->offer->renderPrice('gross'), $point);
                }
                if ($this->offer->getFieldValue('netPrice', false)) {
                  $point = str_replace('{{label}}', __('Net price', 'casawp'), $pattern);
                  echo str_replace('{{value}}', $this->offer->renderPrice('net'), $point);
                }
              }
            }
            break;
          case 'excerpt':
            echo str_replace('{{value}}', $this->offer->getExcerpt(), $pattern_2);
            break;
          case 'availability':
            if ($this->offer->getAvailablility() != 'reference') {
              $value = $this->offer->renderAvailabilityDate();
              if ($value) {
                $point = str_replace('{{label}}', __('Available from:','casawp'), $pattern);
                echo str_replace('{{value}}', $value, $point); 
              }
            }
            break;
          case 'number_of_rooms':
          case 'area_sia_nf':
          case 'area_bwf':
          case 'floor':
          case 'number_of_floors':
          case 'year_built':
          case 'year_renovated':
            $numval = $this->offer->getNumval($field);
            if ($numval) {
              $point = str_replace('{{label}}', $numval->getLabel(), $pattern);
              echo str_replace('{{value}}', $this->offer->renderNumvalValue($numval), $point);
            }
            break;
        }
      } 
    ?>
  </tbody>
</table>