<?php $pattern = '<tr>
  <th>{{label}}</th>
  <td>{{value}}</td>
</tr>' ?>
<?php $pattern_2 = '<tr>
  <td colspan="2">{{value}}</td>
</tr>' ?>

<table class="table">
  <tbody>
    <?php 
      foreach ($datapoints as $datapoint){
        switch (substr($datapoint, strlen('casawp_archive_show_'))) {
          case 'street_and_number':
            $point = str_replace('{{label}}', __('Street', 'casawp'), $pattern);
            echo str_replace('{{value}}', trim($this->offer->getFieldValue('property_address_streetaddress') . ' ' . $this->offer->getFieldValue('property_address_streetnumber')), $point);
            break;
          case 'location':
            $point = str_replace('{{label}}', __('Locality', 'casawp'), $pattern);
            echo str_replace('{{value}}', trim($this->offer->getFieldValue('address_postalcode') . ' ' . $this->offer->getFieldValue('address_locality')), $point);
            break;
          case 'number_of_rooms':
            $numval = $this->offer->getNumval('number_of_rooms');
            if ($numval) {
              $point = str_replace('{{label}}', $numval->getLabel(), $pattern);
              echo str_replace('{{value}}', $this->offer->renderNumvalValue($numval), $point);
            }
            break;
          case 'area_sia_nf':
            $numval = $this->offer->getNumval('area_sia_nf');
            if ($numval) {
              $point = str_replace('{{label}}', $numval->getLabel(), $pattern);
              echo str_replace('{{value}}', $this->offer->renderNumvalValue($numval), $point);
            }
            break;
          case 'area_bwf':
            $numval = $this->offer->getNumval('area_bwf');
            if ($numval) {
              $point = str_replace('{{label}}', $numval->getLabel(), $pattern);
              echo str_replace('{{value}}', $this->offer->renderNumvalValue($numval), $point);
            }
            break;
          case 'surface_property':
            $numval = $this->offer->getNumval('area_sia_gsf');
            if ($numval) {
              $point = str_replace('{{label}}', $numval->getLabel(), $pattern);
              echo str_replace('{{value}}', $this->offer->renderNumvalValue($numval), $point);
            }
            break;
          case 'floor':
            $numval = $this->offer->getNumval('floor');
            if ($numval) {
              $point = str_replace('{{label}}', $numval->getLabel(), $pattern);
              echo str_replace('{{value}}', $this->offer->renderNumvalValue($numval), $point);
            }
            break;
          case 'number_of_floors':
            $numval = $this->offer->getNumval('number_of_floors');
            if ($numval) {
              $point = str_replace('{{label}}', $numval->getLabel(), $pattern);
              echo str_replace('{{value}}', $this->offer->renderNumvalValue($numval), $point);
            }
            break;
          case 'year_built':
            $numval = $this->offer->getNumval('year_built');
            if ($numval) {
              $point = str_replace('{{label}}', $numval->getLabel(), $pattern);
              echo str_replace('{{value}}', $this->offer->renderNumvalValue($numval), $point);
            }
            break;
          case 'year_renovated':
            $numval = $this->offer->getNumval('year_renovated');
            if ($numval) {
              $point = str_replace('{{label}}', $numval->getLabel(), $pattern);
              echo str_replace('{{value}}', $this->offer->renderNumvalValue($numval), $point);
            }
            break;
          case 'price':
            if ($this->offer->getSalestype() == 'buy') {
              $point = str_replace('{{label}}', __('Sales price', 'casawp'), $pattern);
              echo str_replace('{{value}}', $this->offer->renderPrice(), $point);
            }
            if ($this->offer->getSalestype() == 'rent') {
              if ($this->offer->getFieldValue('grossPrice', false)) {
                $point = str_replace('{{label}}', __('Gross price', 'casawp'), $pattern);
                echo str_replace('{{value}}', $this->offer->renderPrice('gross'), $point);
              }
              if ($this->offer->getFieldValue('netPrice', false)) {
                $point = str_replace('{{label}}', __('Net price', 'casawp'), $pattern);
                echo str_replace('{{value}}', $this->offer->renderPrice('net'), $point);
              }
            }
            break;
          case 'excerpt':
            echo str_replace('{{value}}', $this->offer->getExcerpt(), $pattern_2);
            break;
          case 'availability':
            $value = $this->offer->getAvailabilityLabel();
            if ($value) {
              $point = str_replace('{{label}}', __('Availability', 'casawp'), $pattern);
              echo str_replace('{{value}}', $value, $point); 
            }
            break;
        }
      } 
    ?>
  </tbody>
</table>