<?php if ($offers !== null): ?>
	<div class="casawp-similar-properties">
		<h3><?= __('Similar Properties', 'casawp'); ?>
			<div class="casawp-similar-properties-inner">
				<?php foreach ($offers as $key => $post): ?>
					<?php
						global $casawp;
						$offer = $casawp->prepareOffer($post); ?>




					<div class="casawp-property">
						<div class="casawp-thumbnail-wrapper">
							<?php echo (has_post_thumbnail( $post->ID ) ? $offer->renderFeaturedImage() : '<div class="casawp-missing-gallery">' . __('No image', 'casawp') . '</div>'); ?>
						</div>
						<div class="casawp-text">
							<h3><a href="<?= get_permalink($offer->post) ?>"><?php echo $offer->getTitle(); ?></a></h3>
							<table class="table">
							  <tbody>
							    <?php #echo $offer->renderDatapoints('archive', array()) ?>
							  </tbody>
							</table>
						</div>
					</div>





				<?php endforeach; ?>
			</div>
	</div>
<?php endif; ?>