<div class="casawp-single-pagination btn-group btn-group-justified casawp-btn-justified hidden" data-post="<?= $post_id ?>">
	<a href="" class="btn btn-default casawp-single-next" role="button"><i class="fa fa-arrow-left"></i><span> <?= __('Previous','casawp') ?></span></a>
	<a href="" class="btn btn-default casawp-single-archivelink" role="button"><?= __('To list','casawp') ?></a>
	<a href="" class="btn btn-default casawp-single-prev" role="button"><span><?= __('Next','casawp') ?> </span><i class="fa fa-arrow-right"></i></a>
</div>