<div>
  <!-- $urls = $this->getUrls(); -->
  <?php $urls = false ?>

  <ul class="casawp-tabable-nav">
    <li class="active"><a data-toggle="tab" href="#text_basics"><small><?= __("Base data", 'casawp') ?></small></a></li>
    <li><a data-toggle="tab" href="#text_description"><small><?= __('Description', 'casawp') ?></small></a></li>
    <?php if ($urls && array_key_exists('youtube', $urls)) : ?>
      <li><a data-toggle="tab" href="#tab_videos"><small><?= __('Videos', 'casawp') ?></small></a></li>
    <?php endif; ?>
    <li><a data-toggle="tab" href="#text_numbers"><small><?= __("Specifications", 'casawp') ?></small></a></li>
  </ul>
  <div class="casawp-tabable-content">
    <div class="casawp-tabable-pane active in" id="text_basics">
      <div class="casawp-basic-boxes">
          <?= $this->offer->renderBasicBoxes(); ?>
      </div>
      <?= $this->offer->renderMap() ?>
    </div>
    <div class="casawp-tabable-pane" id="text_description">
      <?= $this->offer->renderContent() ?>
    </div>
    <div class="casawp-tabable-pane" id="text_numbers">
      <?= $this->offer->renderDatatable() ?>
    </div>
  </div>
</div>