<div>
  <!-- $urls = $this->getUrls(); -->
  <?php $urls = false ?>

  <ul class="casawp-tabable-nav nav nav-tabs" role="tablist">
    <li class="nav-item"><a class="nav-link active" data-toggle="tab" role="tab" href="#text_basics"><?= __("Base data", 'casawp') ?></a></li>
    <li class="nav-item"><a class="nav-link" data-toggle="tab" role="tab" href="#text_description"><?= __('Description', 'casawp') ?></a></li>
    <?php if ($urls && array_key_exists('youtube', $urls)) : ?>
      <li class="nav-item"><a class="nav-link" data-toggle="tab" role="tab" href="#tab_videos"><?= __('Videos', 'casawp') ?></a></li>
    <?php endif; ?>
    <li class="nav-item"><a class="nav-link" data-toggle="tab" role="tab" href="#text_numbers"><?= __("Specifications", 'casawp') ?></a></li>
  </ul>
  <div class="casawp-tabable-content tab-content bg-faded">
    <div class="casawp-tabable-pane tab-pane fade in active p-a" id="text_basics">
      <?= $this->offer->renderBasicBoxes(); ?>
      <?= $this->offer->renderMap() ?>
    </div>
    <div class="casawp-tabable-pane tab-pane fade p-a" id="text_description">
      <?= $this->offer->renderContent() ?>
    </div>
    <div class="casawp-tabable-pane tab-pane fade p-a" id="text_numbers">
      <?= $this->offer->renderDatatable() ?>
    </div>
  </div>
</div>