<div class="casasync-basic-box">
  <div>
    <h4><?= $offer->renderCategoryLabels() ?></h4>
    <?= $offer->renderDatapoints('single') ?>
  </div>
</div>
<div class="casasync-basic-box">
  <div>
    <h4><?= __("Address", 'casasync') ?></h4>
    <?= $offer->renderAddress() ?>
  </div>
</div>
<div class="casasync-basic-box">
  <div>
      <h4><?= ($offer->type == 'rent') ? (__('rent', 'casasync')) : (__('Price', 'casasync')); ?></h4>
      <?= $this->offer->renderPrice() ?>
  </div>
</div>