<?php if ($sent): ?>
	<p class="alert alert-success">SENT!!!</p>	
<?php else: ?>

	<?= $this->form()->openTag($form->setAttribute('class', 'casasync-contactform-form')); ?>
	<input id="theApsoluteRealEmailField" type="text" name="email" value="" placeholder="NlChT8 AuSf$lLeN">
	<div class="casasync-row">
		<div class="casasync-col-md-5">
			<?= $this->offer->renderContactFormElement($form->get('firstname')) ?>
		</div>
		<div class="casasync-col-md-7">
			<?= $this->offer->renderContactFormElement($form->get('lastname')) ?>
		</div>
	</div>
	<?= $this->offer->renderContactFormElement($form->get('street')) ?>
	<div class="casasync-row">
		<div class="casasync-col-md-5">
			<?= $this->offer->renderContactFormElement($form->get('postal_code')) ?>
		</div>
		<div class="casasync-col-md-7">
			<?= $this->offer->renderContactFormElement($form->get('locality')) ?>
		</div>
	</div>
	<?= $this->offer->renderContactFormElement($form->get('country')) ?>
	<?= $this->offer->renderContactFormElement($form->get('phone')) ?>
	<?= $this->offer->renderContactFormElement($form->get('emailreal')) ?>
	<?= $this->offer->renderContactFormElement($form->get('message')) ?>

	<div class="casasync-row">
	    <div class="casasync-form-group">
	        <div class="casasync-col-md-7">
	            <p class="casasync-form-control-static casasync-text-muted casasync-small">Bitte alle Felder ausfüllen.</p>
	        </div>
	        <div class="casasync-col-md-5">
	            <input type="submit" class="casasync-contactform-send" value="Senden">
	        </div>
	        <div class="clearBoth"></div>
	    </div>
	</div>

	<?= $this->form()->closeTag(); ?>

<?php endif ?>