<?= $this->form()->openTag($form); ?>
<div class="casasync-row">
	<div class="casasync-col-md-5">
		<?= $this->offer->renderContactFormElement($form->get('firstname')) ?>
	</div>
	<div class="casasync-col-md-7">
		<?= $this->offer->renderContactFormElement($form->get('lastname')) ?>
	</div>
</div>
<?= $this->offer->renderContactFormElement($form->get('street')) ?>
<div class="casasync-row">
	<div class="casasync-col-md-5">
		<?= $this->offer->renderContactFormElement($form->get('postal_code')) ?>
	</div>
	<div class="casasync-col-md-7">
		<?= $this->offer->renderContactFormElement($form->get('locality')) ?>
	</div>
</div>
<?= $this->offer->renderContactFormElement($form->get('country')) ?>
<?= $this->offer->renderContactFormElement($form->get('phone')) ?>
<?= $this->offer->renderContactFormElement($form->get('emailreal')) ?>
<?= $this->offer->renderContactFormElement($form->get('message')) ?>

<?= $this->form()->closeTag(); ?>

