<div
    class="form-group <?php if($this->formElementErrors($element)) echo "error" ?>">
    <label><?php echo $element->getLabel() ?></label>
    <?php echo $this->formElement($element->setAttribute('class', 'form-control')); ?>
    <?php if ($this->formElementErrors($element)): ?>
		<span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>    	
    <?php endif ?>
</div>
