<table class="table">
    <tbody>

        <?php if($this->address_street): ?>
            <tr>
                <th><?= __('Street', 'casasync') ?></th>
                <td><?= $this->address_street . ' ' . $this->address_streetnumber ?></td>
            </tr>
        <?php } ?>

    </tbody>
</table>


<?php
/*'casasync_archive_show_street_and_number',
'casasync_archive_show_location',
'casasync_archive_show_number_of_rooms',
'casasync_archive_show_area_sia_nf',
'casasync_archive_show_area_bwf',
'casasync_archive_show_surface_property',
'casasync_archive_show_floor',
'casasync_archive_show_number_of_floors',
'casasync_archive_show_year_built',
'casasync_archive_show_year_renovated',
'casasync_archive_show_price',
'casasync_archive_show_excerpt',
'casasync_archive_show_availability'

###################
  $return .= '<table class="table">';
  $return .= '<tbody>';

  foreach ($value_to_display as $value) {
    switch ($value) {
      case 'casasync_archive_show_street_and_number':
        if($this->address_street){
            $return .= '<tr>'
            .'<th>' . __('Street', 'casasync') . '</th>'
            .'<td>' . $this->address_street . ' ' . $this->address_streetnumber . '</td>'
          .'</tr>';
        }
        break;
      case 'casasync_archive_show_location':
        if ($this->getAddress('property')){
          $return .= '<tr>'
            .'<th>' . __('Locality', 'casasync') . '</th>'
            .'<td>' . $this->getAddress('property', true) . '</td>'
          .'</tr>';
        }
        break;
      case 'casasync_archive_show_number_of_rooms':
        if ($this->getNumval('number_of_rooms')){
          $return .= '<tr>'
            .'<th>' .  __('Number of rooms', 'casasync') . '</th>'
            .'<td>' . $this->getNumval('number_of_rooms') . '</td>'
          .'</tr>';
        }
        break;
      case 'casasync_archive_show_area_sia_nf':
        if ($this->getNumval('area_sia_nf')){
          $return .= '<tr>'
            .'<th>' .  __('Surface usable', 'casasync') . '</th>'
            .'<td>' . $this->getNumval('area_sia_nf') . '</td>'
          .'</tr>';
        }
        break;
      case 'casasync_archive_show_area_bwf':
        if ($this->getNumval('area_bwf')){
          $return .= '<tr>'
            .'<th>' . __('Living space', 'casasync') . '</th>'
            .'<td>' . $this->getNumval('area_bwf', true) . '</td>'
          .'</tr>';
        }
        break;
      case 'casasync_archive_show_surface_property':
        if ($this->getNumval('surface_property')){
          $return .= '<tr>'
            .'<th>' . __('Property space', 'casasync') . '</th>'
            .'<td>' . $this->getNumval('surface_property', true) . '</td>'
          .'</tr>';
        }
        break;
      case 'casasync_archive_show_floor':
        if ($this->floors){
          $return .= '<tr>'
            .'<th>' . __('Floor', 'casasync') . '</th>'
            .'<td>' . $this->floors[0] . '</td>'
          .'</tr>';
        }
        break;
      case 'casasync_archive_show_number_of_floors':
       if ($this->getNumval('number_of_floors')){
          $return .= '<tr>'
            .'<th>' . __('Number of floors', 'casasync') . '</th>'
            .'<td>' . $this->getNumval('number_of_floors', true) . '</td>'
          .'</tr>';
        }
        break;
      case 'casasync_archive_show_year_built':
        if ($this->getNumval('year_built')){
              $return .= '<tr>'
            .'<th>' . __('Year of construction', 'casasync') . '</th>'
            .'<td>' . $this->getNumval('year_built', true) . '</td>'
          .'</tr>';
          }
        break;
      case 'casasync_archive_show_year_renovated':
        if ($this->getNumval('year_renovated')){
          $return .= '<tr>'
            .'<th>' . __('Year of renovation', 'casasync') . '</th>'
            .'<td>' . $this->getNumval('year_renovated', true) . '</td>'
          .'</tr>';
        }
        break;
      case 'casasync_archive_show_price':
        if ($this->availability != 'reference') {
          if ($this->main_basis == 'buy') {
            $return .= '<tr>'
              .'<th>' . __('Sales price','casasync') . '</th>'
            .'<td>';
            $return .= $this->getPrice('sales') ? $this->getPrice('sales', 'full') : __('On Request', 'casasync');
            $return .= '</td>'
            .'</tr>';
          }
          if ($this->main_basis == 'rent') {
            if ( $this->getPrice('gross') || $this->getPrice('net')  ) {
              if ($this->getPrice('gross')) {
                $return .= '<tr>'
                  .'<th>' . __('Gross price','casasync') . '</th>'
                .'<td>';
                $return .= $this->getPrice('gross', 'full');
                $return .= '</td>'
                .'</tr>';
              }
              if ($this->getPrice('net')) {
                $return .= '<tr>'
                  .'<th>' . __('Net price','casasync') . '</th>'
                .'<td>';
                $return .= $this->getPrice('net', 'full');
                $return .= '</td>'
                .'</tr>';
              }
            } else {
              $return .= '<tr>'
                  .'<th>' . __('Rent price','casasync') . '</th>'
                .'<td>';
                $return .=  __('On Request', 'casasync');
                $return .= '</td>'
                .'</tr>';
            }
          }
        }
        break;
        case 'casasync_archive_show_excerpt':
          if($this->getExcerpt()) {
            $return .= '<tr><td colspan="2">' . $this->getExcerpt() . '</td></tr>';
          }
        break;
        case 'casasync_archive_show_availability':
          if ($this->availability != 'reference') {
            if ($this->getAvailabilityLabel()) {
              $return .= '<tr>'
                .'<th>' . __('Available','casasync') . '</th>'
              .'<td>';
              $return .= $this->getAvailabilityLabel();
              $return .= '</td>'
              .'</tr>';
            } else {
              $return .= '<tr>'
                .'<th>' . __('Available','casasync') . '</th>'
              .'<td>';
              $return .= __('On Request', 'casasync');
              $return .= '</td>'
              .'</tr>';
            }
          }
        break;
      default:
        break;
    }
  }
  $return .= '</tbody>';
  $return .= '</table>';
}*/ ?>