<h3><i class="fa fa-briefcase"></i> <?= __('Contact person' , 'casasync') ?></h3><address>
<p>
<?php if ($this->offer->getFieldValue('seller_view_person_givenname', false) && $this->offer->getFieldValue('seller_view_person_familyname', false)) : ?>
  <strong><?= $this->offer->getFieldValue('seller_view_person_givenname') . ' ' . $this->offer->getFieldValue('seller_view_person_familyname') ?></strong>
<?php endif; ?>
<?php if ($this->offer->getFieldValue('seller_view_person_function', false)) : ?>
  <br><i> <?= $this->offer->getFieldValue('seller_view_person_function') ?></i>
<?php endif; ?>
</p>
<?php if(get_option('casasync_show_email_person_view')) : ?>
  <?php if ($this->offer->getFieldValue('seller_view_person_email', false)) : ?>
  <?php 
    $id_number = ($this->reference_id) ? ($this->reference_id) : ($this->casa_id);
    $mailto = 'mailto:' . $this->offer->getFieldValue('seller_view_person_email') . '?subject=Anfrage%20auf%20Objekt-Nr.%20' . $id_number . '&amp;body='
      . rawurlencode(__('I am interested concerning this property. Please contact me.', 'casasync'))
    .'%0A%0ALink:%20' .  get_permalink();
  ?>
  <?= '<p><span class="casasync-label">' . __('Email', 'casasync') . '</span>'
    .'<span class="value break-word"> <a href="' . $mailto . '">' . $this->offer->getFieldValue('seller_view_person_email') . '</a></span></p>'; ?>
  <?php endif; ?>
<?php endif; ?>
<?php if($this->offer->getFieldValue('seller_view_person_phone_direct', false)) : ?>
  <p class="casasync-phone-direct">
    <span class="casasync-label"><?= __('Phone direct', 'casasync') ?></span>
    <span class="value break-word"> <?= $this->offer->getFieldValue('seller_view_person_phone_direct') ?></span></p>
<?php endif; ?>
<?php if($this->offer->getFieldValue('seller_view_person_phone_mobile', false)) : ?>
  <p class="casasync-phone-mobile">
    <span class="casasync-label"><?= __('Mobile', 'casasync') ?></span>
    <span class="value break-word"> <?= $this->offer->getFieldValue('seller_view_person_phone_mobile') ?></span></p>
<?php endif; ?>
</address>