<h3><i class="fa fa-briefcase"></i> <?= __('Provider' , 'casasync') ?></h3>

<address>
  <?= ($this->offer->getFieldValue('seller_org_legalname', false)) ? ('<strong>' . $this->offer->getFieldValue('seller_org_legalname', false) . '</strong><br>') : (''); ?>
  <?= ($this->offer->getFieldValue('seller_org_brand', false)) ? ($this->offer->getFieldValue('seller_org_brand', false) . '<br>') : (''); ?>
  <?= $this->offer->renderSellerAddress(); ?>

  <div class="casasync-seller-infos">
    <?php if(get_option('casasync_show_email_organisation')) : ?>
      <?php if($this->offer->getFieldValue('seller_org_email', false)) : ?>
        <?php 
          $id_number = ($this->reference_id ? $this->reference_id : $this->casa_id);
          $mailto = 'mailto:' . $this->offer->getFieldValue('seller_org_email', false) . '?subject=Anfrage%20auf%20Objekt-Nr.%20' . $id_number . '&amp;body='
          .rawurlencode(__('I am interested concerning this property. Please contact me', 'casasync')) . '%0A%0ALink%20' . get_permalink($this->offer->post);
        ?>
        <p><span class="casasync-label"><?= __('E-Mail', 'casasync') ?></span> 
        <span class="value break-word"> <a href="<?= $mailto ?>"><?= $this->offer->getFieldValue('seller_org_email', false) ?></a></span>
      <?php endif; ?>
    <?php endif; ?>
    <?php if($this->offer->getFieldValue('seller_org_phone_central', false)) : ?>
      <p class="casasync-phone-central">
        <span class="casasync-label"><?= __('Phone', 'casasync')  ?></span>
        <span class="value break-word"> <?= $this->offer->getFieldValue('seller_org_phone_central', false) ?></span>
      </p>
    <?php endif; ?>
    <?php if($this->offer->getFieldValue('seller_org_fax', false)) : ?>
      <p class="casasync-phone-fax">
        <span class="casasync-label"><?= __('Fax', 'casasync')  ?></span>
        <span class="value break-word"> <?= $this->offer->getFieldValue('seller_org_fax', false) ?></span>
      </p>
    <?php endif; ?>
  </div>
</address>