<div>
  <!-- $urls = $this->getUrls(); -->
  <?php $urls = false ?>

  <ul class="casasync-tabable-nav">
    <li class="active"><a data-toggle="tab" href="#text_basics"><small><?= __("Base data", 'casasync') ?></small></a></li>
    <li><a data-toggle="tab" href="#text_description"><small><?= __('Description', 'casasync') ?></small></a></li>
    <?php if ($urls && array_key_exists('youtube', $urls)) : ?>
      <li><a data-toggle="tab" href="#tab_videos"><small><?= __('Videos', 'casasync') ?></small></a></li>
    <?php endif; ?>
    <li><a data-toggle="tab" href="#text_numbers"><small><?= __("Specifications", 'casasync') ?></small></a></li>
  </ul>

  <div class="casasync-tabable-content">

    <div class="casasync-tabable-pane active in" id="text_basics">
      <div class="casasync-basic-boxes">
          <?= $this->offer->renderBasicBoxes(); ?>
      </div>
      <?= $this->offer->renderMap() ?>
    </div>


    <div class="casasync-tabable-pane" id="text_description">
      <?= $this->offer->renderContent() ?>
    </div>

    <div class="casasync-tabable-pane" id="text_numbers">
      <h3><?= __('Offer','casasync') ?></h3>
      <?= $this->offer->renderDatatableOffer() ?>

      <h3><?= __('Property','casasync') ?></h3>
      <?= $this->offer->renderDatatableProperty() ?>


      <?php if ($this->offer->getFeatures()) : ?>
        <div class="casasync-features">
          <h3><?= __('Features','casasync') ?></h3>
          <?= $this->offer->renderFeatures() ?>
        </div>
      <?php endif; ?>

      <?php if ($this->offer->getDistances()) : ?>
        <div class="casasync-distances">
          <h3><?= __('Distances','casasync') ?></h3>
          <?= $this->offer->renderDistances() ?>
        </div>
      <?php endif; ?>

      <?php if ($this->offer->getDocuments()) : ?>
        <div class="casasync-documents">
          <h3><?= __('Documents','casasync') ?></h3>
          <?= $this->offer->getDocuments(); ?>
        </div>
      <?php endif; ?>

      <?php /* ?>
      <?php if ($this->offer->getAllDistances()) { ?>
        <div class="casasync_distances">
          <h3><?= ('Distances','casasync') ?></h3>
          <?= $this->offer->getAllDistances(); ?>
        </div>
      <?php endif; ?>

      <?php if ($this->offer->getUrls()) : ?>
        <div class="casasync_provided_url">
          <h3><?= ('Links','casasync') ?></h3>
          <ul class="casasync-unstyled casasync-links-list">
            <?php foreach ($this->getUrls() as $url_wrapper) : ?>
              <?php foreach ($url_wrapper as $url) :?>
                <li><a href="'.$url['href'].'" target="_blank" title="'.$url['title'].'">'. ($url['label'] ? $url['label'] : $url['href']) .'</a></li>
              <?php endforeach; ?>
            <?php endforeach; ?>
          </ul>
        </div>
      <?php endif; ?>

      <?php */ ?>

    </div>

  </div>
</div>